"""initial schema

Revision ID: 321332d3af8b
Revises: 
Create Date: 2026-01-29 12:50:04.890249

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '321332d3af8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('validation_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_file_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('high_confidence', sa.Integer(), nullable=True),
    sa.Column('medium_confidence', sa.Integer(), nullable=True),
    sa.Column('low_confidence', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_approve_threshold', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('manual_review_threshold', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('validator_config',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('validator_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('cost_per_1000_requests', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('entity_name_original', sa.String(length=500), nullable=True),
    sa.Column('address1_original', sa.String(length=500), nullable=True),
    sa.Column('address2_original', sa.String(length=500), nullable=True),
    sa.Column('address3_original', sa.String(length=500), nullable=True),
    sa.Column('city_original', sa.String(length=255), nullable=True),
    sa.Column('state_original', sa.String(length=50), nullable=True),
    sa.Column('zip_original', sa.String(length=20), nullable=True),
    sa.Column('country_original', sa.String(length=50), nullable=True),
    sa.Column('entity_name_osm', sa.String(length=500), nullable=True),
    sa.Column('address1_osm', sa.String(length=500), nullable=True),
    sa.Column('address2_osm', sa.String(length=500), nullable=True),
    sa.Column('city_osm', sa.String(length=255), nullable=True),
    sa.Column('state_osm', sa.String(length=50), nullable=True),
    sa.Column('zip_osm', sa.String(length=20), nullable=True),
    sa.Column('zip4_osm', sa.String(length=10), nullable=True),
    sa.Column('country_osm', sa.String(length=50), nullable=True),
    sa.Column('osm_source', sa.String(length=50), nullable=True),
    sa.Column('fields_filled_by_osm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fields_corrected_by_osm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('osm_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fill_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('correction_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('entity_name_ora', sa.String(length=500), nullable=True),
    sa.Column('address1_ora', sa.String(length=500), nullable=True),
    sa.Column('address2_ora', sa.String(length=500), nullable=True),
    sa.Column('address3_ora', sa.String(length=500), nullable=True),
    sa.Column('address4_ora', sa.String(length=500), nullable=True),
    sa.Column('city_ora', sa.String(length=255), nullable=True),
    sa.Column('state_ora', sa.String(length=50), nullable=True),
    sa.Column('zip_ora', sa.String(length=20), nullable=True),
    sa.Column('country_ora', sa.String(length=50), nullable=True),
    sa.Column('fill_stage', sa.String(length=20), nullable=True),
    sa.Column('entity_name_validated', sa.String(length=500), nullable=True),
    sa.Column('address1_validated', sa.String(length=500), nullable=True),
    sa.Column('address2_validated', sa.String(length=500), nullable=True),
    sa.Column('city_validated', sa.String(length=255), nullable=True),
    sa.Column('state_validated', sa.String(length=50), nullable=True),
    sa.Column('zip_validated', sa.String(length=20), nullable=True),
    sa.Column('zip4_validated', sa.String(length=10), nullable=True),
    sa.Column('county_validated', sa.String(length=100), nullable=True),
    sa.Column('country_validated', sa.String(length=50), nullable=True),
    sa.Column('usps_delivery_line_1', sa.String(length=500), nullable=True),
    sa.Column('usps_delivery_line_2', sa.String(length=500), nullable=True),
    sa.Column('usps_last_line', sa.String(length=255), nullable=True),
    sa.Column('usps_formatted_full', sa.Text(), nullable=True),
    sa.Column('address_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_parse_success', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('has_geocoding', sa.Boolean(), nullable=True),
    sa.Column('entity_name_from_address', sa.String(length=500), nullable=True),
    sa.Column('entity_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('entity_dba_name', sa.String(length=500), nullable=True),
    sa.Column('overall_confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('record_status', sa.String(length=50), nullable=True),
    sa.Column('validation_source', sa.String(length=100), nullable=True),
    sa.Column('validator_priority', sa.Integer(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.Column('is_po_box', sa.Boolean(), nullable=True),
    sa.Column('is_residential', sa.Boolean(), nullable=True),
    sa.Column('is_valid_usps', sa.Boolean(), nullable=True),
    sa.Column('missing_entity_name_original', sa.Boolean(), nullable=True),
    sa.Column('missing_address1_original', sa.Boolean(), nullable=True),
    sa.Column('missing_city_original', sa.Boolean(), nullable=True),
    sa.Column('missing_state_original', sa.Boolean(), nullable=True),
    sa.Column('missing_zip_original', sa.Boolean(), nullable=True),
    sa.Column('missing_country_original', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_entity_name', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_address1', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_city', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_state', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_zip', sa.Boolean(), nullable=True),
    sa.Column('osm_filled_country', sa.Boolean(), nullable=True),
    sa.Column('trans_entity_name_uppercase', sa.Boolean(), nullable=True),
    sa.Column('trans_state_to_code', sa.Boolean(), nullable=True),
    sa.Column('trans_address_abbrev', sa.Boolean(), nullable=True),
    sa.Column('trans_directional_fix', sa.Boolean(), nullable=True),
    sa.Column('trans_zip_plus4', sa.Boolean(), nullable=True),
    sa.Column('completeness_original', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('completeness_osm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('completeness_oracle', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('validation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['validation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('review_queue',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('suggested_correction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolution_action', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['validation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('validation_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('validation_step', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('validation_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('history_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['validation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_history')
    op.drop_table('review_queue')
    op.drop_table('entities')
    op.drop_table('validator_config')
    op.drop_table('validation_jobs')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
